[package]
name = "linon"
version = "0.1.0"
authors = ["Niklas Korz <niklas@niklaskorz.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = { version = "0.25", features = ["web-sys"] }
cgmath = "0.18"
log = "0.4"
futures = "0.3"
bytemuck = { version = "1.5", features = ["derive"] }
anyhow = "1.0"
notify = "5.0.0-pre.9"
tobj = "3.0"
# GUI
egui = "0.12"
epi = "0.12"

[dependencies.wgpu]
git = "https://github.com/gfx-rs/wgpu-rs"
rev = "7486bdad64bb5d17b709ecccb41e063469efff88"

[dependencies.egui_wgpu_backend]
git = "https://github.com/niklaskorz/egui_wgpu_backend"
rev = "0fda4e328bbdc83b5cf45ab967eaf5421436f9af"

[dependencies.egui_winit_platform]
git = "https://github.com/hasenbanck/egui_winit_platform"
rev = "9fd92782d8de22d7882168d7b5ae7a2eb02448d9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "=0.3.50", features = [] }
