[package]
name = "linon"
version = "0.1.0"
authors = ["Niklas Korz <niklas@niklaskorz.de>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = { version = "0.25", features = ["web-sys"] }
cgmath = "0.18"
log = "0.4"
futures = "0.3"
bytemuck = { version = "1.5", features = ["derive"] }
anyhow = "1.0"
tobj = "3.0"
egui = "0.14"
egui_winit_platform = "0.10"
wgpu = "0.10"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
notify = "5.0.0-pre.13"
env_logger = "0.9"
egui_wgpu_backend = "0.12"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.77"
wasm-bindgen-futures = "0.4.27"
web-sys = "0.3.22"
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
egui_wgpu_backend = { version = "0.12", features = ["web"] }

[patch.crates-io]
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", rev = "e8c236cd71cf7ee9ea5e4533e01b88692fc15991" }
egui_wgpu_backend = { git = "https://github.com/hasenbanck/egui_wgpu_backend.git", rev = "74f63a071ff6578688f18d8091bf549d417b2c8f" }
