[package]
name = "linon"
version = "1.0.0"
authors = ["Niklas Korz <niklas@niklaskorz.de>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = { version = "0.25", features = ["web-sys"] }
cgmath = "0.18"
log = "0.4"
futures = "0.3"
bytemuck = { version = "1.5", features = ["derive"] }
anyhow = "1.0"
tobj = "3.0"
egui = "0.15"
egui_winit_platform = "0.11"
wgpu = "0.11"
syntect = { version = "4", default-features = false, features = ["default-fancy"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
notify = "5.0.0-pre.13"
env_logger = "0.9"
egui_wgpu_backend = "0.14"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.77"
wasm-bindgen-futures = "0.4.27"
web-sys = "0.3.22"
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
egui_wgpu_backend = { version = "0.14", features = ["web"] }
