[package]
name = "linon"
version = "1.0.0"
authors = ["Niklas Korz <niklas@niklaskorz.de>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.26"
cgmath = "0.18"
log = "0.4"
futures = "0.3"
bytemuck = { version = "1.5", features = ["derive"] }
anyhow = "1.0"
tobj = "3.0"
egui = "0.18"
egui-winit = "0.18"
egui-wgpu = "0.18"
wgpu = "0.13"
syntect = { version = "4", default-features = false, features = ["default-fancy"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
notify = "5.0.0-pre.13"
env_logger = "0.9"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.77"
wasm-bindgen-futures = "0.4.27"
web-sys = "0.3.22"
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"

[features]

[patch.crates-io]
egui= { git = "https://github.com/emilk/egui.git", rev = "c062bca6eeac3c8db3aecfbaa99172e1c74da9fc" }
egui-winit = { git = "https://github.com/emilk/egui.git", rev = "c062bca6eeac3c8db3aecfbaa99172e1c74da9fc" }
egui-wgpu = { git = "https://github.com/emilk/egui.git", rev = "c062bca6eeac3c8db3aecfbaa99172e1c74da9fc" }
