[package]
name = "linon"
version = "0.1.0"
authors = ["Niklas Korz <niklas@niklaskorz.de>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.25"
cgmath = "0.18"
log = "0.4"
futures = "0.3"
bytemuck = { version = "1.5", features = ["derive"] }
anyhow = "1.0"
notify = "5.0.0-pre.9"
tobj = "3.0"
egui = "0.13"
egui_winit_platform = "0.9"
egui_wgpu_backend = "0.11"
wgpu = "0.10"
env_logger = "0.9"
